name: YAML lint
on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        run: |
          python - <<'PY'
          import yaml, pathlib, sys
          for p in pathlib.Path('.').rglob('*.yaml'):
              try:
                  yaml.safe_load(p.read_text(encoding='utf-8'))
                  print(f'✓ {p}')
              except yaml.YAMLError as e:
                  print(f'❌ {p}: {e}')
                  sys.exit(1)
          PY
